Repository AbhiPatel10/openzone, pull requests merged in 2024-05, with the labels that each got.

#25 Added responsiveness to features section
  src/components/FeatureSection/page.tsx
Labels: gssoc, level1

#49 updated button design, background design and text.
  src/components/HeroSection/page.tsx
Labels: gssoc, level1, Under Review

#58 fixed the grid issue
  .gitignore
  src/app/projects/page.tsx
  src/styles/global.css
Labels: gssoc, level1, Under Review

#63 menu Icon added!
  src/components/Navbar/page.tsx
Labels: gssoc, level1, Under Review

#68 Create greetings.yaml
  .github/workflows/greetings.yaml
Labels: gssoc, level1, Under Review

#67 [Feature] Update Footer Design #2
  pnpm-lock.yaml
  src/components/Footer/page.tsx
Labels: gssoc, level1, Under Review

#79 Closes #23 Added Contact Us Page
  public/images/contactus.png
  src/app/ContactSection/page.tsx
  src/components/Footer/page.tsx
  src/components/Navbar/page.tsx
Labels: gssoc, level2, Under Review

#111 mobile size navbar isuue solved
  src/components/Navbar/page.tsx
Labels: gssoc, level2

#108 Added "Privacy Policy and Terms and Conditions" Pages
  src/app/PrivacyPolicy/page.tsx
  src/app/TermsAndConditions/page.tsx
  src/components/Footer/page.tsx
Labels: Under Review

#117 Navbar issue solved in mobile design
  src/components/Navbar/page.tsx
Labels: gssoc, level1

#128 header-sticky
  src/components/Navbar/page.tsx
Labels: gssoc, level1

#112 Feat/Update social links
  src/components/Footer/page.tsx
Labels: Under Review

#100 fixes search error #99
  src/app/projects/page.tsx
Labels: Under Review

#132 feat: add codeql workflow for typescript
  .github/workflows/codeql.yml
Labels: enhancement, gssoc, level2
